# Generated by Django 3.2.5 on 2021-07-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='fax_number',
        ),
    ]
