# Generated by Django 3.2.5 on 2021-07-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0003_mymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files'),
        ),
    ]
